# Generated by Django 5.0.7 on 2024-07-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_email_product_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='email',
            new_name='descrption',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
    ]
